/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programa;

import Lógica.*;
import javax.swing.*;
import java.util.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author 
 */
public class MapaKar2Variables extends javax.swing.JFrame {

    private int numVariables;
    private String tipoExpresion;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MapaKar2Variables.class.getName());
    
    private javax.swing.JButton[][] gridButtons = new javax.swing.JButton[2][2]; 

    public MapaKar2Variables(int numVariables, String tipoExpresion) {
        this.numVariables = numVariables;
        this.tipoExpresion = tipoExpresion;
        initComponents();
        inicializarTablero(); 
        this.setLocationRelativeTo(null);
        this.setTitle("Mapa de Karnaugh - 2 Variables");
    }

    public MapaKar2Variables() {
        this(2, "SOP"); 
    }

    /**
     * Genera la cuadrícula de 2x2 en el panelMapa
     */
    private void inicializarTablero() {
        panelMapa.removeAll();
        // 2 filas, 2 columnas para 2 variables
        panelMapa.setLayout(new java.awt.GridLayout(2, 2, 2, 2));
        
        ActionListener toggleAction = (ActionEvent e) -> {
            JButton btn = (JButton) e.getSource();
            if (btn.getText().equals("0")) {
                btn.setText("1");
                btn.setBackground(new Color(255, 105, 97)); //ESTO es cyan, no se cual es el color del mapa de 4 variables, es lo más cercano que pude
            } else {
                btn.setText("0");
                btn.setBackground(Color.WHITE);
            }
        };

        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 2; j++) {
                JButton btn = new JButton("0");
                btn.setFont(new Font("Segoe UI", Font.BOLD, 18));
                btn.setBackground(Color.WHITE);
                btn.setFocusPainted(false);
                btn.addActionListener(toggleAction);

                gridButtons[i][j] = btn; 
                panelMapa.add(btn); 
            }
        }
        panelMapa.revalidate();
        panelMapa.repaint();
    }

   
    // Lógica de cálculo para 2 variables

    private void calcularSimplificacion() {
        try {
            Simplificador simplificador = new Simplificador(numVariables);
            List<Integer> minterms = new ArrayList<>();

            int[][] mapaIndices = {
                {0, 1},
                {2, 3}
            };

            for (int i = 0; i < 2; i++) {
                for (int j = 0; j < 2; j++) {
                    String valor = gridButtons[i][j].getText();
                    int indiceReal = mapaIndices[i][j];

                    if (tipoExpresion.equalsIgnoreCase("SOP")) {
                        if (valor.equals("1")) minterms.add(indiceReal);
                    } else { 
                        if (valor.equals("0")) minterms.add(indiceReal);
                    }
                }
            }

            if (minterms.isEmpty()) {
                JOptionPane.showMessageDialog(this, "F = " + (tipoExpresion.equals("SOP") ? "0" : "1"));
                return;
            }

            List<Term> implicantesOptimos = QuineMcCluskey.simplificar(minterms, numVariables);
            String resultado = simplificador.construirExpresion(implicantesOptimos, tipoExpresion);
            
            JOptionPane.showMessageDialog(this, "Resultado Simplificado (" + tipoExpresion + "):\nF = " + resultado, 
                    "Cálculo Exitoso", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error en el cálculo", e);
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelMapa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 45, 83));

        jPanel1.setBackground(new java.awt.Color(23, 45, 83));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("MAPA DE KARNAUGH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jButton3.setText("Volver");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nota: Hacer click en el cuadro correspondiente para cambiar el valor entre 1 y 0");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("B");
        jLabel12.setToolTipText("");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("A");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("0");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 37, -1));

        jLabel10.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("1");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 37, -1));

        panelMapa.setLayout(new java.awt.GridLayout(4, 4));
        jPanel1.add(panelMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 226, 133));

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("0");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 37, -1));

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 37, -1));

        jButton2.setText("Calcular");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        MenuConfiguracion menu = new MenuConfiguracion ();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        calcularSimplificacion();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MapaKar2Variables().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelMapa;
    // End of variables declaration//GEN-END:variables
}
