/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programa;

/**
 *
 * @author Alexd
 */
import javax.swing.JOptionPane;
public class MenuConfiguracion extends javax.swing.JFrame {
    
    // VARIABLES DE CONFIGURACIÓN
    private int numVariables = 2;      
    private String tipoExpresion = "SOP";

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuConfiguracion.class.getName());

    /**
     * Creates new form MenuConfiguracion
     */
    public MenuConfiguracion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbVariables = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rbtnSOP = new javax.swing.JRadioButton();
        rbtnPOS = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(385, 450));

        jPanel1.setBackground(new java.awt.Color(23, 45, 83));
        jPanel1.setPreferredSize(new java.awt.Dimension(375, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(23, 45, 83));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIMPLIFICADOR DE EXPRESIONES");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 24));

        jLabel3.setBackground(new java.awt.Color(23, 45, 83));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NÚMERO DE VARIABLES");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 115, -1, -1));

        cmbVariables.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbVariables.setForeground(new java.awt.Color(44, 62, 80));
        cmbVariables.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opciones", "2 Variables", "3 Variables", "4 Variables" }));
        cmbVariables.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 160, 130), 1, true));
        cmbVariables.addActionListener(this::cmbVariablesActionPerformed);
        jPanel1.add(cmbVariables, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 110, -1, -1));

        jLabel4.setBackground(new java.awt.Color(23, 45, 83));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIPO DE EXPRESIÓN");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 169, -1, -1));

        rbtnSOP.setBackground(new java.awt.Color(23, 45, 83));
        buttonGroup2.add(rbtnSOP);
        rbtnSOP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnSOP.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSOP.setText("SOP");
        rbtnSOP.setOpaque(true);
        rbtnSOP.addActionListener(this::rbtnSOPActionPerformed);
        jPanel1.add(rbtnSOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 198, -1, -1));

        rbtnPOS.setBackground(new java.awt.Color(23, 45, 83));
        buttonGroup2.add(rbtnPOS);
        rbtnPOS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnPOS.setForeground(new java.awt.Color(255, 255, 255));
        rbtnPOS.setText("POS");
        rbtnPOS.addActionListener(this::rbtnPOSActionPerformed);
        jPanel1.add(rbtnPOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 198, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VARIABLES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        lblA.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        lblA.setForeground(new java.awt.Color(107, 141, 213));
        lblA.setText("A");
        jPanel1.add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 45, -1));

        lblB.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        lblB.setForeground(new java.awt.Color(107, 141, 213));
        lblB.setText("B");
        jPanel1.add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 45, -1));

        lblC.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        lblC.setForeground(new java.awt.Color(107, 141, 213));
        lblC.setText("C");
        jPanel1.add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        lblD.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        lblD.setForeground(new java.awt.Color(107, 141, 213));
        lblD.setText("D");
        jPanel1.add(lblD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        btnConfirmar.setBackground(new java.awt.Color(55, 105, 194));
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 364, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 359, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 365, 13));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 252, 365, 11));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVariablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVariablesActionPerformed
        
   numVariables = cmbVariables.getSelectedIndex() + 1;

    
    lblA.setVisible(false);
    lblB.setVisible(false);
    lblC.setVisible(false);
    lblD.setVisible(false);

    if (numVariables == 2) {
        lblA.setVisible(true);
        lblB.setVisible(true);
    } else if (numVariables == 3) {
        lblA.setVisible(true);
        lblB.setVisible(true);
        lblC.setVisible(true);
    } else if (numVariables == 4) {
        lblA.setVisible(true);
        lblB.setVisible(true);
        lblC.setVisible(true);
        lblD.setVisible(true);
    }
        
    }//GEN-LAST:event_cmbVariablesActionPerformed

    private void rbtnSOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSOPActionPerformed
         tipoExpresion = "SOP";
    }//GEN-LAST:event_rbtnSOPActionPerformed

    private void rbtnPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPOSActionPerformed
        tipoExpresion = "POS";
    }//GEN-LAST:event_rbtnPOSActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        
    
    if (cmbVariables.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Seleccione el número de variables");
        return;
    }

   
        switch (numVariables) {
            case 2:
                
                MapaKar2Variables v2 = new MapaKar2Variables(numVariables, tipoExpresion);
                v2.setVisible(true);
                break;

            case 3:
                
                MapaKar3Variables v3 = new MapaKar3Variables(numVariables, tipoExpresion);
                v3.setVisible(true);
                break;

            case 4:
                
                MapaKar4Variables v4 = new MapaKar4Variables(numVariables, tipoExpresion);
                v4.setVisible(true);
                break;

            default:
                JOptionPane.showMessageDialog(this, "Error en la selección.");
                return;
            
        }

    // Opcional: cerrar esta
    this.dispose();
    
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuConfiguracion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbVariables;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblD;
    private javax.swing.JRadioButton rbtnPOS;
    private javax.swing.JRadioButton rbtnSOP;
    // End of variables declaration//GEN-END:variables
}
