/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programa;
import Lógica.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author Alexd
 */
public class VentanaTablaVerdad extends javax.swing.JFrame {
    
    private int numVariables;
    private String tipoExpresion;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelMapa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("MAPA DE KARNAUGH");

        jLabel2.setText("Nota: Hacer clik en el cuadro correspondiente para cambiar el valor entre 1 y 0");

        jButton1.setText("Calcular");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        panelMapa.setLayout(new java.awt.GridLayout(4, 4));

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel3.setText("00");

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel4.setText("11");

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel5.setText("01");

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel6.setText("10");

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel7.setText("00");

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel8.setText("11");

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel9.setText("10");

        jLabel10.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel10.setText("01");

        jLabel11.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel11.setText("AB");
        jLabel11.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel12.setText("CD");
        jLabel12.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11))
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel8)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public VentanaTablaVerdad(int numVariables, String tipoExpresion) {
        this.numVariables = numVariables;
        this.tipoExpresion = tipoExpresion;
        initComponents();
        inicializarTablero();
        this.setLocationRelativeTo(null);
    }

    private javax.swing.JButton[][] gridButtons = new javax.swing.JButton[4][4];
    private void inicializarTablero() {
        // Tu panelMapa ya tiene GridLayout(4,4) desde el diseño.
        
        // Listener compartido (la acción al hacer click)
        java.awt.event.ActionListener toggleAction = new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                javax.swing.JButton btn = (javax.swing.JButton) e.getSource();
                if (btn.getText().equals("0")) {
                    btn.setText("1");
                    btn.setBackground(java.awt.Color.CYAN); // Opcional: color
                } else if (btn.getText().equals("1")) {
                    btn.setText("0");
                    btn.setBackground(java.awt.Color.WHITE); // Opcional
                }
            }
        };

        // Bucle para crear los 16 botones y meterlos al panel
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                javax.swing.JButton btn = new javax.swing.JButton("0");
                btn.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Letra grande
                btn.setBackground(java.awt.Color.WHITE);
                
                // Añadir el evento de click
                btn.addActionListener(toggleAction);

                // 1. Guardarlo en TU matriz (para lógica)
                gridButtons[i][j] = btn; 

                // 2. Añadirlo VISUALMENTE al panel que arrastraste
                panelMapa.add(btn); 
            }
        }
        
        // Refrescar para asegurar que se vean
        panelMapa.revalidate();
        panelMapa.repaint();
    }
    private void calcularSimplificacion() {
    try {
        // 1. Instanciar tu Simplificador (De tu paquete Lógica)
        Simplificador simplificador = new Simplificador(numVariables);
        
        // 2. Extraer los datos de los botones visuales
        List<Integer> minterms = new ArrayList<>();

        // Matriz para mapear coordenadas visuales a índices reales (Gray Code -> Binario)
        // Ajustado para 4 variables. Si es 3 o 2, se usarán solo las filas/cols necesarias.
        int[][] mapaIndices = {
            {0,  1,  3,  2},   // AB=00
            {4,  5,  7,  6},   // AB=01
            {12, 13, 15, 14},  // AB=11 (Fila 3 visual)
            {8,  9,  11, 10}   // AB=10 (Fila 4 visual)
        };

        // Recorremos los botones
        // Nota: Asegúrate de que 'gridButtons' esté lleno (ver paso anterior de inicializarTablero)
        int filasVisuales = (numVariables == 2) ? 1 : (numVariables == 3) ? 2 : 4;
        int colsVisuales = (numVariables < 2) ? 2 : 4; 
        // Ajuste rápido: Para K-Map, 2 vars es 2x2? O 1x4?
        // Asumiremos tu grid 4x4 y limitaremos según vars.
        
        // RECORRIDO DE TU GRID DE BOTONES
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                // Verificar límites según número de variables para no leer botones ocultos
                // (Esta lógica depende de cómo ocultaste/mostraste los botones, 
                //  pero si usas el mapeo completo no pasa nada si ignoras los índices altos)
                
                JButton btn = gridButtons[i][j]; // Tu matriz de botones
                int indiceReal = mapaIndices[i][j]; // El número binario real (0-15)
                
                String valor = btn.getText();

                // LÓGICA SOP (Suma de Productos) -> Buscamos los 1
                if (tipoExpresion.equals("SOP")) {
                    if (valor.equals("1")) {
                        minterms.add(indiceReal);
                    }
                } 
                // LÓGICA POS (Producto de Sumas) -> Buscamos los 0
                else { 
                    if (valor.equals("0")) {
                        minterms.add(indiceReal);
                    }
                }
            }
        }

        // 3. ¡LLAMAR A TU LÓGICA EXISTENTE!
        // Usamos QuineMcCluskey directamente ya que Simplificador.java espera int[][]
        // pero aquí ya extrajimos la lista limpia.
        
        if (minterms.isEmpty()) {
            mostrarResultado("0"); // O "1" dependiendo si es POS/SOP vacío
            return;
        }

        List<Term> primos = QuineMcCluskey.generarPrimos(minterms, numVariables);
        
        // Usamos el método de tu clase Simplificador para convertir a texto
        // (Asegúrate de haberlo hecho public como dije en el Paso 1)
        String resultado = simplificador.construirExpresion(primos, tipoExpresion);

        // Si es POS, el resultado matemático necesita formato (A+B) en vez de AB
        // Tu lógica actual genera formato SOP (A'B + C). 
        // Para POS real necesitarías invertir lógica de Morgan, pero por ahora mostremos el resultado base.
        
        // 4. Mostrar resultado
        mostrarResultado(resultado);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al calcular: " + e.getMessage());
    }
}

private void mostrarResultado(String texto) {
    // Aquí puedes ponerlo en un JLabel, o abrir un JOptionPane
    JOptionPane.showMessageDialog(this, "La expresión simplificada es:\n\nF = " + texto, "Resultado", JOptionPane.INFORMATION_MESSAGE);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:                                           
    calcularSimplificacion();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelMapa;
    // End of variables declaration//GEN-END:variables
}
